server.port=8080
server.forward-headers-strategy=native

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/chess}
spring.datasource.username=${DB_USER:chess}
spring.datasource.password=${DB_PASSWORD:chess}

spring.flyway.enabled=true
